version: '3.8'

services:
  # Web server with basic authentication
  nginx:
    image: nginx:latest
    container_name: quiz-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-content:/usr/share/nginx/html:ro
      - ./auth/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - webapp
    networks:
      - quiz-network

  # Your web application container
  webapp:
    build: ./webapp
    container_name: quiz-webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - quiz-network

  # Local Git server (Gitea)
  gitea:
    image: gitea/gitea:latest
    container_name: quiz-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__HTTP_PORT=3001
      - GITEA__server__ROOT_URL=http://localhost:3001/
    restart: always
    ports:
      - "3001:3001"
      - "2222:22"
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - quiz-network

volumes:
  gitea-data:

networks:
  quiz-network:
    driver: bridge