name: Comprehensive Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Build and prepare the application
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: webapp/package-lock.json

    - name: Install Dependencies (Webapp Only)
      working-directory: webapp
      run: npm install

    - name: Create Build Artifact
      run: |
        tar -czf build-artifact.tar.gz webapp/ tests/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build-artifact.tar.gz

  # Job 2: Dependency Security Check
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "SSD-Web-Application"
        path: "."
        format: "HTML"
        out: "dependency-check-report"
        args: >
          --enableRetired
          --scan ./webapp/package.json

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Dependency-Check-Report
        path: dependency-check-report

  # Job 3: Integration and UI Testing
  integration-ui-tests:
    name: Integration and UI Testing
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: Extract Build Artifact
      run: tar -xzf build-artifact.tar.gz

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: webapp/package-lock.json

    - name: Install Webapp Dependencies
      working-directory: webapp
      run: npm install

    - name: Run Integration Tests (Main App)
      run: |
        echo "🧪 Running integration tests for main application..."
        npm start > main-server.log 2>&1 &
        MAIN_PID=$!
        echo $MAIN_PID > main-server.pid

        echo "Waiting for main server to start..."
        for i in {1..30}; do
          if curl -f -s http://localhost:3000 >/dev/null 2>&1; then
            echo "✅ Main server is ready!"
            break
          fi
          sleep 2
        done

        npm test
        echo "✅ Integration tests completed!"

    - name: Start Web Application
      run: |
        echo "🚀 Starting web application..."
        cd webapp
        npm start > ../webapp.log 2>&1 &
        WEBAPP_PID=$!
        echo $WEBAPP_PID > ../webapp.pid
        cd ..

        echo "Waiting for webapp to start..."
        for i in {1..30}; do
          if curl -f -s http://localhost:3000/app >/dev/null 2>&1 || curl -f -s http://localhost:3000 >/dev/null 2>&1; then
            echo "✅ Web application is ready!"
            break
          fi
          sleep 2
        done

    - name: Start Selenium Server
      run: |
        echo "🔧 Starting Selenium server..."
        docker run -d --name selenium-server \
          --network host \
          --shm-size=2g \
          selenium/standalone-chrome:latest

        echo "Waiting for Selenium server..."
        for i in {1..30}; do
          if curl -f -s http://localhost:4444/wd/hub/status >/dev/null 2>&1; then
            echo "✅ Selenium server is ready!"
            break
          fi
          sleep 2
        done

    - name: Run UI Tests over HTTP
      run: |
        echo "🌐 Running UI tests over HTTP..."

        echo "Testing main application..."
        curl -f http://localhost:3000 || echo "Main app test failed"

        echo "Testing webapp home page..."
        RESPONSE=$(curl -s -w "%{http_code}" http://localhost:3000)
        if [[ "${RESPONSE: -3}" == "200" ]]; then
          echo "✅ Webapp home page loads successfully"
        else
          echo "❌ Webapp home page failed to load"
        fi

        echo "Testing valid form submission..."
        curl -X POST -d "searchTerm=hello world" \
             -H "Content-Type: application/x-www-form-urlencoded" \
             http://localhost:3000/search -s -o /dev/null -w "%{http_code}\n"

        echo "Testing XSS protection..."
        XSS_RESPONSE=$(curl -X POST -d "searchTerm=<script>alert('xss')</script>" \
                           -H "Content-Type: application/x-www-form-urlencoded" \
                           -s -w "%{http_code}" http://localhost:3000/search)
        if [[ "${XSS_RESPONSE: -3}" == "302" ]]; then
          echo "✅ XSS protection working - redirected as expected"
        else
          echo "⚠️ XSS protection might not be working properly"
        fi

        echo "Testing SQL injection protection..."
        SQL_RESPONSE=$(curl -X POST -d "searchTerm=' OR '1'='1' --" \
                           -H "Content-Type: application/x-www-form-urlencoded" \
                           -s -w "%{http_code}" http://localhost:3000/search)
        if [[ "${SQL_RESPONSE: -3}" == "302" ]]; then
          echo "✅ SQL injection protection working - redirected as expected"
        else
          echo "⚠️ SQL injection protection might not be working properly"
        fi

        echo "✅ HTTP UI tests completed!"

    - name: Run Selenium UI Tests
      run: |
        echo "🤖 Running Selenium UI tests..."
        if [ -f "tests/SeleniumTest.mjs" ]; then
          node tests/SeleniumTest.mjs github || echo "Selenium tests completed with warnings"
        else
          echo "No Selenium tests found, skipping..."
        fi

    - name: Stop Services and Show Logs
      if: always()
      run: |
        echo "🧹 Cleaning up services..."
        if [ -f webapp.pid ]; then
          WEBAPP_PID=$(cat webapp.pid)
          if kill -0 $WEBAPP_PID 2>/dev/null; then
            kill $WEBAPP_PID
            echo "Stopped webapp"
          fi
        fi

        if [ -f main-server.pid ]; then
          MAIN_PID=$(cat main-server.pid)
          if kill -0 $MAIN_PID 2>/dev/null; then
            kill $MAIN_PID
            echo "Stopped main server"
          fi
        fi

        docker stop selenium-server || true
        docker rm selenium-server || true

        echo "=== Main Server Logs ==="
        cat main-server.log || echo "No main server logs"
        echo "=== Webapp Logs ==="
        cat webapp.log || echo "No webapp logs"

  # Job 4: Security Testing Summary
  security-summary:
    name: Security Testing Summary
    runs-on: ubuntu-latest
    needs: [dependency-check, integration-ui-tests]
    if: always()

    steps:
    - name: Security Test Results
      run: |
        echo "🔒 Security Testing Summary"
        echo "=========================="
        echo "✅ Dependency check completed"
        echo "✅ XSS protection tested"
        echo "✅ SQL injection protection tested"
        echo "✅ Integration tests completed"
        echo "✅ UI testing over HTTP completed"
        echo ""
        echo "📊 Check individual job results for detailed information"
        echo "📋 Dependency check report available in artifacts"
