name: Automated Testing with Unit and Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Create Build Artifact
      run: |
        tar -czf build-artifact.tar.gz package.json package-lock.json src/ tests/
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build-artifact.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        
    - name: Extract Build Artifact
      run: tar -xzf build-artifact.tar.gz
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        npm test
        echo "Unit tests completed!"
      
    - name: Start Application in Background
      run: |
        echo "Starting Node.js application..."
        npm start &
        sleep 5
        echo "Application started, testing connectivity..."
        curl http://localhost:3000 || exit 1
        echo "Application is responding!"
        
    - name: Verify Selenium Server is Ready
      run: |
        echo "Checking Selenium server status..."
        curl -f http://localhost:4444/wd/hub/status
        echo "Selenium server is ready!"
        
    - name: Run Selenium Integration Tests
      run: |
        echo "Running Selenium integration tests..."
        node tests/SeleniumTest.mjs github
        echo "Selenium tests completed!"
        
    - name: Stop Application
      if: always()
      run: |
        echo "Stopping application..."
        pkill -f "node src/server.js" || true
        echo "Application stopped!"